image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      opam pin add faraday https://github.com/dakotamurphyucf/faraday.git -y
      opam pin add faraday-async https://github.com/dakotamurphyucf/faraday.git -y
      opam pin add gluten https://github.com/anmonteiro/gluten.git -y
      opam pin add gluten-async https://github.com/anmonteiro/gluten.git -y
      opam pin add httpaf https://github.com/dakotamurphyucf/httpaf.git -y
      opam pin add httpaf-async https://github.com/dakotamurphyucf/httpaf.git -y
      opam pin add websocketaf https://github.com/dakotamurphyucf/websocketaf.git -y
      opam pin add websocketaf-async https://github.com/dakotamurphyucf/websocketaf.git -y
      opam pin https://github.com/dakotamurphyucf/ocaml-caqti.git -y -n
      opam install -y core async ppx_jane ppx_log ppx_expect pythonlib ppx_bin_prot ppx_csv_conv ppx_python ppx_sexp_value ppx_sexp_message ppx_yojson_conv uri httpaf-async websocketaf-async ppx_rapper_async caqti-driver-postgresql
      dune build
  - command: eval $(opam env)
vscode:
  extensions:
    - ocamllabs.ocaml-platform
    - eamodio.gitlens

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod